import React, { createContext, useState, useContext, ReactNode } from 'react';

type Language = 'vi' | 'en';

interface SettingsContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  isDarkMode: boolean;
  setIsDarkMode: (val: boolean) => void;
  t: (key: string) => string;
}

const translations = {
  vi: {
    hello: 'Xin chào',
    search_placeholder: 'Tìm kiếm: Bác sĩ, chuyên khoa, toa thuốc,...',
    featured_packages: 'Gói khám nổi bật',
    see_all: 'Xem tất cả',
    services: 'Dịch vụ',
    utilities: 'Tiện ích',
    specialties: 'Chuyên khoa',
    general_internal: 'Nội Tổng quát',
    pediatrics: 'Nhi khoa',
    obstetrics: 'Phụ & Sản khoa',
    musculoskeletal: 'Cơ xương khớp',
    cardiology: 'Tim mạch',
    neurology: 'Thần kinh',
    dermatology: 'Da liễu',
    imaging: 'Chẩn đoán hình ảnh',
    test_results: 'Tra cứu kết quả',
    receipts: 'Hóa đơn &\nBiên lai',
    info_guide: 'Thông tin\nhướng dẫn',
    medical_info: 'Thông tin y\nkhoa',
    online_consult: 'Tư vấn trực tuyến',
    book_appointment: 'Đặt lịch khám',
    medical_records: 'Hồ sơ y tế',
    support: 'Hỗ trợ CSKH',
    upcoming_appointment: 'Lịch khám sắp tới',
    confirmed: 'Đã xác nhận',
    dr: 'Bác sĩ',
    pkg_basic_male: 'Khám Tổng Quát Cơ Bản - Nam',
    pkg_basic_female: 'Khám Tổng Quát Cơ Bản - Nữ',
    pkg_cancer_screen: 'Tầm soát Ung thư Vú & Cổ tử cung',
    pkg_heart: 'Khám chuyên sâu Tim mạch',
    booked: 'đã đặt',
    profile: 'Cá nhân',
    my_profile: 'Hồ sơ của tôi',
    logout: 'Đăng xuất',
    notifications: 'Thông báo',
    no_notifications: 'Không có thông báo nào',
    calendar: 'Lịch khám',
    no_appointments: 'Không có lịch khám nào sắp tới',
    month: 'Tháng',
    book_pkg: 'Đăng ký khám theo gói',
    manage_appt: 'Quản lý lịch khám',
    upcoming: 'Sắp tới',
    history: 'Lịch sử',
    medical_history: 'Lịch sử khám bệnh',
    no_history: 'Bạn chưa có lịch sử khám bệnh nào.',
    choose_specialty: 'Chọn Chuyên khoa',
    account_info: 'Thông tin tài khoản',
    auth_status: 'Trạng thái',
    auth_success: 'Hồ sơ của bạn đã được xác thực bởi bệnh viện. Bạn có toàn quyền truy cập hồ sơ y tế.',
    auth_warning: 'Hồ sơ chưa được xác thực. Hãy đến bệnh viện để xác thực.',
    approved: 'Đã duyệt',
    pending: 'Chưa duyệt',
    patient_records: 'Hồ sơ bệnh nhân',
    updating: 'Đang cập nhật',
    verified: 'Đã xác thực',
    unverified: 'Chưa xác thực',
    manage_records: 'Quản lý hồ sơ',
    general_settings: 'Cài đặt chung',
    security_account: 'BẢO MẬT & TÀI KHOẢN',
    change_password: 'Đổi mật khẩu',
    delete_account: 'Xóa tài khoản',
    delete_confirm_title: 'Xác nhận',
    delete_confirm_msg: 'Bạn có chắc chắn muốn xóa tài khoản? Hành động này không thể hoàn tác.',
    delete_btn: 'Xóa',
    access_denied: 'Từ chối truy cập',
    access_denied_msg: 'Vui lòng mang CCCD đến quầy lễ tân bệnh viện để xác thực tài khoản trước khi xem hồ sơ mật.',
    username_phone: 'Tên đăng nhập / Số điện thoại',
    display_name: 'Họ và tên hiển thị',
    enter_display_name: 'Nhập tên hiển thị',
    email: 'Email liên hệ',
    enter_email: 'Nhập email',
    security: 'Bảo mật',
    biometrics_login: 'Đăng nhập bằng sinh trắc học',
    biometrics_desc: 'Sử dụng FaceID/TouchID để đăng nhập',
    phone_unchangeable_msg: 'Số điện thoại không thể thay đổi vì dùng để định danh tài khoản.',
    save: 'Lưu',
    success: 'Thành công',
    account_updated: 'Thông tin tài khoản đã được cập nhật.',
    ui_customization: 'TÙY CHỈNH GIAO DIỆN',
    language: 'Ngôn ngữ',
    vietnamese: 'Tiếng Việt',
    english: 'English',
    dark_mode: 'Chế độ tối (Dark Mode)',
    dark_mode_desc: 'Tiết kiệm pin và bảo vệ mắt',
    app_notifications: 'THÔNG BÁO ỨNG DỤNG',
    push_notifications: 'Nhận thông báo Đẩy (Push)',
    push_desc: 'Lịch khám, kết quả xét nghiệm',
    system: 'HỆ THỐNG',
    clear_cache: 'Xóa bộ nhớ đệm',
    cache_desc: 'MB đang sử dụng',
    app_version: 'Phiên bản ứng dụng',
    version: 'Phiên bản',
    clear_cache_title: 'Xóa bộ nhớ đệm',
    clear_cache_msg: 'Bạn có chắc chắn muốn xóa bộ nhớ đệm của ứng dụng? Quá trình này sẽ giúp ứng dụng chạy mượt hơn.',
    freed_cache: 'Đã giải phóng 45MB bộ nhớ đệm.',
    phone_placeholder: 'Số điện thoại',
    password_placeholder: 'Mật khẩu',
    login_btn: 'Đăng nhập',
    quick_login: 'Hoặc đăng nhập nhanh bằng',
    no_account: 'Bạn chưa có tài khoản? ',
    register_btn: 'Đăng ký',
    forgot_password_btn: 'Quên mật khẩu?',
    register_title: 'Đăng ký tài khoản',
    have_account: 'Bạn đã có tài khoản? ',
    confirm_password_placeholder: 'Nhập lại mật khẩu',
    forgot_password_title: 'Khôi phục mật khẩu',
    forgot_password_desc: 'Vui lòng nhập số điện thoại hoặc email đã đăng ký. Chúng tôi sẽ gửi mã OTP để đặt lại mật khẩu.',
    send_otp_btn: 'Gửi mã OTP',
    back_to_login: 'Quay lại đăng nhập',
    otp_title: 'Xác thực OTP',
    otp_desc: 'Vui lòng nhập mã gồm 6 chữ số đã được gửi đến số điện thoại của bạn',
    confirm: 'Xác nhận',
    not_received: 'Chưa nhận được mã? ',
    resend: 'Gửi lại',
    back_to_register: 'Quay lại Đăng ký',
    completed: 'Hoàn thành',
    cancelled: 'Đã hủy',
    appointment_detail: 'Chi tiết lịch khám',
    thank_you_service: 'Cảm ơn bạn đã tin tưởng dịch vụ của chúng tôi',
    reception_code: 'Mã tiếp nhận',
    appointment_info_title: 'Thông tin lịch khám',
    specialty: 'Chuyên khoa',
    dr_label: 'Bác sĩ',
    exam_date: 'Ngày khám',
    expected_time: 'Giờ dự kiến',
    clinic_room: 'Phòng khám',
    expected_fee: 'Phí khám (dự kiến)',
    room_102: 'Phòng 102 - Tầng 1',
    doctors: 'Bác sĩ',
    tests: 'Xét nghiệm',
    exam_ticket: 'Phiếu khám',
    prescription: 'Toa thuốc',
    invoice: 'Hóa đơn',
    ultrasound: 'Siêu âm',
    no_data: 'Chưa có dữ liệu',
    search_modal_placeholder: 'Tìm kiếm: Bác sĩ, chuyên khoa, toa thuốc,...',
    specialty_doctors: 'Bác sĩ chuyên khoa',
    book_btn: 'Đặt khám',
    reviews: 'đánh giá',
    new_password_diff: 'Mật khẩu mới của bạn phải khác biệt với các mật khẩu đã sử dụng trước đây để đảm bảo an toàn.',
    current_password: 'Mật khẩu hiện tại',
    new_password: 'Mật khẩu mới',
    reenter_new_password: 'Nhập lại mật khẩu mới',
    enter_password: 'Nhập mật khẩu',
    update_password: 'Cập nhật mật khẩu',
    specialty_exam: 'Khám chuyên khoa',
    package_exam: 'Khám theo gói',
    time_slots: 'KHUNG GIỜ',
    health_packages: 'Gói khám sức khỏe',
    package_desc_title: 'Chọn gói khám phù hợp với nhu cầu chăm sóc sức khỏe của bạn.',
    details: 'Chi tiết',
    package_detail: 'Chi tiết Gói khám',
    has_results_today: 'Có kết quả trong ngày',
    general_desc: 'Mô tả chung',
    service_includes: 'Chi tiết dịch vụ gồm có',
    total_cost: 'Tổng chi phí',
    book_package: 'Đặt gói khám',
    manage_records_desc: 'Bạn có thể tạo và quản lý hồ sơ khám bệnh cho người thân tại đây. Vui lòng mang giấy tờ tùy thân đến bệnh viện để xác thực hồ sơ nếu chưa được duyệt.',
    records_list: 'Danh sách hồ sơ',
    self: 'Bản thân',
    father: 'Bố',
    add_new_record: 'Thêm hồ sơ mới',
    patient_records_management: 'Quản lý hồ sơ bệnh nhân',
  },
  en: {
    hello: 'Hello',
    search_placeholder: 'Search: Doctors, specialties, prescriptions...',
    featured_packages: 'Featured Packages',
    see_all: 'See all',
    services: 'Services',
    utilities: 'Utilities',
    specialties: 'Specialties',
    general_internal: 'General Internal',
    pediatrics: 'Pediatrics',
    obstetrics: 'Obstetrics',
    musculoskeletal: 'Musculoskeletal',
    cardiology: 'Cardiology',
    neurology: 'Neurology',
    dermatology: 'Dermatology',
    imaging: 'Imaging Diagnostics',
    test_results: 'Test Results',
    receipts: 'Receipts',
    info_guide: 'Guidelines',
    medical_info: 'Medical Info',
    online_consult: 'Online Consult',
    book_appointment: 'Book Appt.',
    medical_records: 'Medical Records',
    support: 'Customer Support',
    upcoming_appointment: 'Upcoming Appointment',
    confirmed: 'Confirmed',
    dr: 'Dr.',
    pkg_basic_male: 'Basic General Checkup - Male',
    pkg_basic_female: 'Basic General Checkup - Female',
    pkg_cancer_screen: 'Breast & Cervical Cancer Screening',
    pkg_heart: 'Advanced Cardiology Checkup',
    booked: 'booked',
    profile: 'Profile',
    my_profile: 'My Profile',
    logout: 'Logout',
    notifications: 'Notifications',
    no_notifications: 'No notifications yet',
    calendar: 'Calendar',
    no_appointments: 'No upcoming appointments',
    month: 'Month',
    book_pkg: 'Book a Health Package',
    manage_appt: 'Manage Appointments',
    upcoming: 'Upcoming',
    history: 'History',
    medical_history: 'Medical History',
    no_history: 'You have no medical history yet.',
    choose_specialty: 'Choose Specialty',
    account_info: 'Account Information',
    auth_status: 'Status',
    auth_success: 'Your profile has been verified by the hospital. You have full access to medical records.',
    auth_warning: 'Profile unverified. Please visit the hospital to verify.',
    approved: 'Approved',
    pending: 'Pending',
    patient_records: 'Patient Records',
    updating: 'Updating',
    verified: 'Verified',
    unverified: 'Unverified',
    manage_records: 'Manage Records',
    general_settings: 'General Settings',
    security_account: 'SECURITY & ACCOUNT',
    change_password: 'Change Password',
    delete_account: 'Delete Account',
    delete_confirm_title: 'Confirm',
    delete_confirm_msg: 'Are you sure you want to delete your account? This action cannot be undone.',
    delete_btn: 'Delete',
    access_denied: 'Access Denied',
    access_denied_msg: 'Please bring your ID to the hospital reception to verify your account before accessing confidential records.',
    username_phone: 'Username / Phone Number',
    display_name: 'Display Name',
    enter_display_name: 'Enter display name',
    email: 'Contact Email',
    enter_email: 'Enter email',
    security: 'Security',
    biometrics_login: 'Biometrics Login',
    biometrics_desc: 'Use FaceID/TouchID to login',
    phone_unchangeable_msg: 'Phone number cannot be changed as it is used for account identification.',
    save: 'Save',
    success: 'Success',
    account_updated: 'Account information has been updated.',
    ui_customization: 'UI CUSTOMIZATION',
    language: 'Language',
    vietnamese: 'Tiếng Việt',
    english: 'English',
    dark_mode: 'Dark Mode',
    dark_mode_desc: 'Save battery and protect eyes',
    app_notifications: 'APP NOTIFICATIONS',
    push_notifications: 'Push Notifications',
    push_desc: 'Appointments, test results',
    system: 'SYSTEM',
    clear_cache: 'Clear Cache',
    cache_desc: 'MB in use',
    app_version: 'App Version',
    version: 'Version',
    clear_cache_title: 'Clear Cache',
    clear_cache_msg: 'Are you sure you want to clear the app cache? This will help the app run smoother.',
    freed_cache: 'Cleared 45MB of cache.',
    phone_placeholder: 'Phone number',
    password_placeholder: 'Password',
    login_btn: 'Login',
    quick_login: 'Or quick login with',
    no_account: 'Don\'t have an account? ',
    register_btn: 'Register',
    forgot_password_btn: 'Forgot password?',
    register_title: 'Register Account',
    have_account: 'Already have an account? ',
    confirm_password_placeholder: 'Confirm password',
    forgot_password_title: 'Password Recovery',
    forgot_password_desc: 'Please enter your registered phone number or email. We will send an OTP to reset your password.',
    send_otp_btn: 'Send OTP',
    back_to_login: 'Back to Login',
    otp_title: 'OTP Verification',
    otp_desc: 'Please enter the 6-digit code sent to your phone number',
    confirm: 'Confirm',
    not_received: 'Haven\'t received the code? ',
    resend: 'Resend',
    back_to_register: 'Back to Register',
    completed: 'Completed',
    cancelled: 'Cancelled',
    appointment_detail: 'Appointment Details',
    thank_you_service: 'Thank you for trusting our service',
    reception_code: 'Reception Code',
    appointment_info_title: 'Appointment Information',
    specialty: 'Specialty',
    dr_label: 'Doctor',
    exam_date: 'Date',
    expected_time: 'Expected Time',
    clinic_room: 'Clinic Room',
    expected_fee: 'Expected Fee',
    room_102: 'Room 102 - Floor 1',
    doctors: 'Doctors',
    tests: 'Tests',
    exam_ticket: 'Medical Slip',
    prescription: 'Prescription',
    invoice: 'Invoice',
    ultrasound: 'Ultrasound',
    no_data: 'No data available',
    search_modal_placeholder: 'Search: Doctor, specialty, prescription...',
    specialty_doctors: 'Specialty Doctors',
    book_btn: 'Book',
    reviews: 'reviews',
    new_password_diff: 'Your new password must be different from previously used passwords for security.',
    current_password: 'Current Password',
    new_password: 'New Password',
    reenter_new_password: 'Re-enter New Password',
    enter_password: 'Enter password',
    update_password: 'Update Password',
    specialty_exam: 'Specialty Exam',
    package_exam: 'Package Exam',
    time_slots: 'TIME SLOTS',
    health_packages: 'Health Packages',
    package_desc_title: 'Choose a package that suits your healthcare needs.',
    details: 'Details',
    package_detail: 'Package Details',
    has_results_today: 'Results same day',
    general_desc: 'General Description',
    service_includes: 'Service Includes',
    total_cost: 'Total Cost',
    book_package: 'Book Package',
    manage_records_desc: 'You can create and manage medical records for your relatives here. Please bring your ID to the hospital to verify the profile if it has not been approved.',
    records_list: 'Records List',
    self: 'Self',
    father: 'Father',
    add_new_record: 'Add New Record',
    patient_records_management: 'Patient Records Management',
  }
};

const SettingsContext = createContext<SettingsContextType>({
  language: 'vi',
  setLanguage: () => {},
  isDarkMode: false,
  setIsDarkMode: () => {},
  t: (key: string) => key,
});

export const SettingsProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('vi');
  const [isDarkMode, setIsDarkMode] = useState(false);

  const t = (key: string) => {
    return (translations[language] as any)[key] || key;
  };

  return (
    <SettingsContext.Provider value={{ language, setLanguage, isDarkMode, setIsDarkMode, t }}>
      {children}
    </SettingsContext.Provider>
  );
};

export const useSettings = () => useContext(SettingsContext);
